#!/bin/bash
# Ahmed Aly, 400557252
# SE2XC3
# This script compares two arguments as integers and prints the smaller one

# Checks to see if only 2 numbers were inputed, if not and/or if they are the same, if so exit
if [ $# -ne 2 ] || [ "$1" -eq "$2" ]; then

    echo "Error: Need exactly 2 different numbers" >&2
    exit 1
    
# Checks if the first number is smaller in value, if so it prints it, else prints the second number
elif [ $1 -lt $2 ]; then

    echo "$1"
    
else
    echo "$2"
    
fi
