all: hello goodbye reflection

hello: hello.c
	gcc -o hello hello.c

goodbye: goodbye.c
	gcc -o goodbye goodbye.c

reflection: reflection.c
	gcc -o reflection reflection.c

clean:
	rm -f hello goodbye reflection
