name: SE2XC3 Labs Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update -y && sudo apt-get install -y build-essential

    - name: Build week01
      run: make -C week01 all
    - name: Build week02
      run: make -C week02 all
